version: '3.2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<%= DBPASSWORD %>
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
  node:
    image: node:8.2.1
    volumes:
      - .:/var/app:cached
      - /var/app/node_modules
    working_dir: /var/app
    command: [sh, -c, yarn install]
    depends_on:
      - web